import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';

import { Brand } from '@/components/Brand';
import { Screen } from '@/components/Screen';
import { useColorScheme } from '@/components/useColorScheme';
import { addContribution, createGoal, createRecurring, deleteBudget, deleteExpense, deleteGoal, deleteIncome, deleteRecurring, getBudget, getCashFlowProjection, getGoals, getRecurring, getTransactions, isExpense, setBudget, updateRecurring, type CashFlowProjection, type Expense, type FinancialGoal, type Income, type MonthlyBudget, type RecurringTransaction } from '@/core/api/finance-api';
import { useAuth } from '@/core/auth/auth-context';
import { palette, radius } from '@/constants/Colors';

const money = (value: number | string) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value));
const initialMonth = new Date().toISOString().slice(0, 7);
const categories = ['FOOD', 'TRANSPORT', 'RENT', 'LEISURE', 'HEALTH', 'OTHER'];

export default function Finances() {
  const colors = palette[useColorScheme() ?? 'light'];
  const { authorizedRequest } = useAuth();
  const [selectedMonth, setSelectedMonth] = useState(initialMonth);
  const [entries, setEntries] = useState<Array<Income | Expense>>([]);
  const [budget, setBudgetState] = useState<MonthlyBudget | null>(null);
  const [goals, setGoals] = useState<FinancialGoal[]>([]);
  const [recurring, setRecurring] = useState<RecurringTransaction[]>([]);
  const [projection, setProjection] = useState<CashFlowProjection | null>(null);
  const [budgetCategory, setBudgetCategory] = useState('FOOD');
  const [budgetAmount, setBudgetAmount] = useState('');
  const [goalName, setGoalName] = useState('');
  const [goalAmount, setGoalAmount] = useState('');
  const [recurringDescription, setRecurringDescription] = useState('');
  const [recurringAmount, setRecurringAmount] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    try {
      const [nextEntries, nextBudget, nextGoals, nextRecurring, nextProjection] = await Promise.all([
        authorizedRequest(token => getTransactions(token, selectedMonth)), authorizedRequest(token => getBudget(token, selectedMonth)), authorizedRequest(getGoals), authorizedRequest(getRecurring), authorizedRequest(token => getCashFlowProjection(token)),
      ]);
      setEntries(nextEntries); setBudgetState(nextBudget); setGoals(nextGoals); setRecurring(nextRecurring); setProjection(nextProjection);
    } catch { Alert.alert('Não foi possível carregar o planejamento', 'Tente novamente em instantes.'); }
    finally { setLoading(false); }
  }, [authorizedRequest, selectedMonth]);
  useEffect(() => { void load(); }, [load]);
  const expenseTotal = useMemo(() => entries.filter(isExpense).reduce((sum, item) => sum + Number(item.amount), 0), [entries]);

  async function saveBudget() { const amount = Number(budgetAmount.replace(/\./g, '').replace(',', '.')); if (!amount || amount < 0) return Alert.alert('Valor inválido', 'Informe um limite maior ou igual a zero.'); setSaving(true); try { await authorizedRequest(token => setBudget(token, budgetCategory, amount, selectedMonth)); setBudgetAmount(''); await load(); } catch { Alert.alert('Não foi possível salvar o orçamento', 'Tente novamente.'); } finally { setSaving(false); } }
  async function saveGoal() { const amount = Number(goalAmount.replace(/\./g, '').replace(',', '.')); if (!goalName.trim() || !amount || amount <= 0) return Alert.alert('Meta incompleta', 'Informe nome e valor da meta.'); setSaving(true); try { const targetDate = `${new Date().getFullYear() + 1}-12-31`; await authorizedRequest(token => createGoal(token, { name: goalName.trim(), targetAmount: amount, currentAmount: 0, targetDate })); setGoalName(''); setGoalAmount(''); await load(); } catch { Alert.alert('Não foi possível criar a meta', 'Tente novamente.'); } finally { setSaving(false); } }
  async function saveRecurring() { const amount = Number(recurringAmount.replace(/\./g, '').replace(',', '.')); if (!recurringDescription.trim() || !amount || amount <= 0) return Alert.alert('Recorrência incompleta', 'Informe descrição e valor.'); setSaving(true); try { await authorizedRequest(token => createRecurring(token, { kind: 'EXPENSE', description: recurringDescription.trim(), amount, category: 'OTHER', frequency: 'MONTHLY', startDate: `${selectedMonth}-01`, endDate: null })); setRecurringDescription(''); setRecurringAmount(''); await load(); } catch { Alert.alert('Não foi possível criar a recorrência', 'Tente novamente.'); } finally { setSaving(false); } }
  async function contribute(goal: FinancialGoal) { const amount = Number(goal.requiredMonthlyContribution); if (!amount || amount <= 0) return Alert.alert('Meta concluída', 'Esta meta não precisa de novo aporte.'); try { await authorizedRequest(token => addContribution(token, goal.id, { amount, contributionDate: new Date().toISOString().slice(0, 10), note: 'Aporte mobile' })); await load(); } catch { Alert.alert('Não foi possível registrar o aporte', 'Tente novamente.'); } }
  async function removeEntry(entry: Income | Expense) { try { await authorizedRequest(token => isExpense(entry) ? deleteExpense(token, entry.id) : deleteIncome(token, entry.id)); await load(); } catch { Alert.alert('Não foi possível remover o lançamento', 'Tente novamente.'); } }
  async function deleteCategoryBudget(category: string) { try { await authorizedRequest(token => deleteBudget(token, category, selectedMonth)); await load(); } catch { Alert.alert('Não foi possível remover o orçamento', 'Tente novamente.'); } }
  async function removeGoal(goal: FinancialGoal) { try { await authorizedRequest(token => deleteGoal(token, goal.id)); await load(); } catch { Alert.alert('Não foi possível remover a meta', 'Tente novamente.'); } }
  async function toggleRecurring(item: RecurringTransaction) { try { await authorizedRequest(token => updateRecurring(token, item.id, { description: item.description, amount: Number(item.amount), category: item.category, endDate: item.endDate, active: !item.active })); await load(); } catch { Alert.alert('Não foi possível atualizar a recorrência', 'Tente novamente.'); } }
  async function removeRecurring(item: RecurringTransaction) { try { await authorizedRequest(token => deleteRecurring(token, item.id)); await load(); } catch { Alert.alert('Não foi possível remover a recorrência', 'Tente novamente.'); } }

  return <Screen refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); void load(); }} tintColor={colors.primary} />}>
    <Brand /><View><Text style={[s.title, { color: colors.text }]}>Planejamento</Text><Text style={[s.muted, { color: colors.textMuted }]}>Orçamento, metas e futuro financeiro em um só lugar.</Text></View>
    <View style={[s.hero, { backgroundColor: colors.primary }]}><Text style={s.heroLabel}>Despesas registradas no mês</Text><Text style={s.heroValue}>{money(expenseTotal)}</Text><View style={s.monthRow}><Pressable onPress={() => setSelectedMonth(shiftMonth(selectedMonth, -1))}><Text style={s.monthButton}>‹</Text></Pressable><Text style={s.monthLabel}>{formatMonth(selectedMonth)}</Text><Pressable onPress={() => setSelectedMonth(shiftMonth(selectedMonth, 1))}><Text style={s.monthButton}>›</Text></Pressable></View></View>
    <SectionTitle title="Lançamentos do mês" colors={colors} /><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{entries.length ? entries.map(entry => { const expense = isExpense(entry); return <View key={entry.id} style={s.budgetRow}><View style={{ flex: 1 }}><Text style={[s.name, { color: colors.text }]}>{entry.description}</Text><Text style={[s.muted, { color: colors.textMuted }]}>{entry.transactionDate}{expense ? ` · ${entry.category}` : ' · Receita'}</Text></View><Text style={[s.amount, { color: expense ? colors.danger : colors.positive }]}>{expense ? '− ' : '+ '}{money(entry.amount)}</Text><Pressable onPress={() => router.push({ pathname: '/transaction-edit' as any, params: { id: entry.id, kind: expense ? 'expense' : 'income' } })}><Text style={[s.link, { color: colors.primary }]}>Editar</Text></Pressable><Pressable onPress={() => void removeEntry(entry)}><Text style={[s.remove, { color: colors.danger }]}>Remover</Text></Pressable></View>; }) : <Text style={[s.muted, { color: colors.textMuted }]}>Nenhum lançamento neste mês.</Text>}</View>
    <SectionTitle title="Orçamento mensal" colors={colors} /><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[s.summary, { color: colors.text }]}>{budget ? `${money(budget.totalSpent)} gastos de ${money(budget.totalPlanned)}` : 'Nenhum orçamento definido'}</Text>{budget?.categories.map(item => <View key={item.category} style={s.budgetRow}><View style={{ flex: 1 }}><Text style={[s.name, { color: colors.text }]}>{item.name}</Text><Text style={[s.muted, { color: colors.textMuted }]}>{money(item.spent)} / {money(item.planned)}</Text></View><Text style={[s.percent, { color: Number(item.usagePercentage) >= 100 ? colors.danger : colors.primary }]}>{Math.round(Number(item.usagePercentage))}%</Text><Pressable onPress={() => void deleteCategoryBudget(item.category)}><Text style={[s.remove, { color: colors.danger }]}>Remover</Text></Pressable></View>)}<Text style={[s.label, { color: colors.textMuted }]}>Definir limite por categoria</Text><View style={s.inline}>{<SelectChips values={categories} selected={budgetCategory} onSelect={setBudgetCategory} colors={colors} />}<TextInput value={budgetAmount} onChangeText={setBudgetAmount} keyboardType="decimal-pad" placeholder="0,00" placeholderTextColor={colors.textMuted} style={[s.smallInput, { color: colors.text, borderColor: colors.border }]} /></View><Button label="Salvar orçamento" onPress={() => void saveBudget()} colors={colors} disabled={saving} /></View>
    <SectionTitle title="Metas financeiras" colors={colors} /><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{goals.map(goal => <View key={goal.id} style={s.goal}><View style={s.inline}><View style={{ flex: 1 }}><Text style={[s.name, { color: colors.text }]}>{goal.name}</Text><Text style={[s.muted, { color: colors.textMuted }]}>{money(goal.currentAmount)} de {money(goal.targetAmount)} · {Math.round(Number(goal.progressPercentage))}%</Text></View><Pressable onPress={() => void contribute(goal)}><Text style={[s.link, { color: colors.primary }]}>Aportar</Text></Pressable><Pressable onPress={() => void removeGoal(goal)}><Text style={[s.remove, { color: colors.danger }]}>Remover</Text></Pressable></View><View style={[s.progress, { backgroundColor: colors.surfaceMuted }]}><View style={[s.progressFill, { backgroundColor: colors.primary, width: `${Math.min(100, Number(goal.progressPercentage))}%` }]} /></View></View>)}<Field placeholder="Nome da meta" value={goalName} onChangeText={setGoalName} colors={colors} /><Field placeholder="Valor alvo" value={goalAmount} onChangeText={setGoalAmount} keyboardType="decimal-pad" colors={colors} /><Button label="Criar meta" onPress={() => void saveGoal()} colors={colors} disabled={saving} /></View>
    <SectionTitle title="Recorrências" colors={colors} /><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{recurring.map(item => <View key={item.id} style={s.budgetRow}><View style={{ flex: 1 }}><Text style={[s.name, { color: colors.text }]}>{item.description}</Text><Text style={[s.muted, { color: colors.textMuted }]}>{money(item.amount)} · {item.frequency === 'MONTHLY' ? 'Mensal' : item.frequency}</Text></View><Text style={[s.status, { color: item.active ? colors.positive : colors.textMuted }]}>{item.active ? 'Ativa' : 'Pausada'}</Text><Pressable onPress={() => void toggleRecurring(item)}><Text style={[s.link, { color: colors.primary }]}>{item.active ? 'Pausar' : 'Ativar'}</Text></Pressable><Pressable onPress={() => void removeRecurring(item)}><Text style={[s.remove, { color: colors.danger }]}>Remover</Text></Pressable></View>)}<Field placeholder="Descrição da recorrência" value={recurringDescription} onChangeText={setRecurringDescription} colors={colors} /><Field placeholder="Valor mensal" value={recurringAmount} onChangeText={setRecurringAmount} keyboardType="decimal-pad" colors={colors} /><Button label="Criar recorrência mensal" onPress={() => void saveRecurring()} colors={colors} disabled={saving} /></View>
    <SectionTitle title="Projeção de caixa" colors={colors} /><View style={[s.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{projection ? <><Text style={[s.summary, { color: colors.text }]}>Saldo projetado: {money(projection.projectedCumulativeBalance)}</Text>{projection.items.slice(0, 6).map(item => <View key={item.referenceMonth} style={s.budgetRow}><Text style={[s.name, { color: colors.text }]}>{item.referenceMonth}</Text><Text style={[s.muted, { color: Number(item.projectedNet) >= 0 ? colors.positive : colors.danger }]}>{money(item.projectedNet)}</Text></View>)}</> : <ActivityIndicator color={colors.primary} />}</View>
    <Pressable onPress={() => router.push('/create')} style={[s.cta, { backgroundColor: colors.primary }]}><Text style={s.ctaText}>+ Adicionar lançamento</Text></Pressable>
  </Screen>;
}
function shiftMonth(value: string, delta: number): string { const date = new Date(`${value}-01T12:00:00Z`); date.setUTCMonth(date.getUTCMonth() + delta); return date.toISOString().slice(0, 7); }
function formatMonth(value: string): string { return new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${value}-01T12:00:00Z`)); }
function SectionTitle({ title, colors }: { title: string; colors: typeof palette.light }) { return <Text style={[s.section, { color: colors.text }]}>{title}</Text>; }
function Field({ colors, ...props }: { colors: typeof palette.light } & React.ComponentProps<typeof TextInput>) { return <TextInput {...props} placeholderTextColor={colors.textMuted} style={[s.input, { color: colors.text, borderColor: colors.border }]} />; }
function Button({ label, onPress, colors, disabled }: { label: string; onPress: () => void; colors: typeof palette.light; disabled: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[s.button, { backgroundColor: colors.primary }, disabled && s.disabled]}>{disabled ? <ActivityIndicator color="#fff" /> : <Text style={s.buttonText}>{label}</Text>}</Pressable>; }
function SelectChips({ values, selected, onSelect, colors }: { values: string[]; selected: string; onSelect: (value: string) => void; colors: typeof palette.light }) { return <View style={s.chips}>{values.map(value => <Pressable key={value} onPress={() => onSelect(value)} style={[s.chip, { backgroundColor: value === selected ? colors.primary : colors.primarySoft }]}><Text style={{ color: value === selected ? '#fff' : colors.primary, fontFamily: 'Inter_700Bold', fontSize: 11 }}>{value}</Text></Pressable>)}</View>; }
const s = StyleSheet.create({ title: { fontFamily: 'Inter_800ExtraBold', fontSize: 28, letterSpacing: -.8 }, muted: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19 }, hero: { borderRadius: radius.card, padding: 20, gap: 7 }, heroLabel: { color: '#fff', fontFamily: 'Inter_500Medium', fontSize: 13 }, heroValue: { color: '#fff', fontFamily: 'Inter_800ExtraBold', fontSize: 29 }, monthRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, monthButton: { color: '#fff', fontFamily: 'Inter_800ExtraBold', fontSize: 25, paddingHorizontal: 12 }, monthLabel: { color: '#fff', fontFamily: 'Inter_700Bold', fontSize: 14, textTransform: 'capitalize' }, section: { fontFamily: 'Inter_700Bold', fontSize: 19, marginTop: 4 }, card: { borderWidth: 1, borderRadius: radius.component, padding: 16, gap: 13 }, label: { fontFamily: 'Inter_700Bold', fontSize: 13 }, summary: { fontFamily: 'Inter_700Bold', fontSize: 16 }, budgetRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, amount: { fontFamily: 'Inter_700Bold', fontSize: 13 }, percent: { fontFamily: 'Inter_800ExtraBold', fontSize: 14 }, status: { fontFamily: 'Inter_700Bold', fontSize: 12 }, inline: { flexDirection: 'row', alignItems: 'center', gap: 8 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, flex: 1 }, chip: { paddingHorizontal: 8, paddingVertical: 7, borderRadius: radius.pill }, smallInput: { width: 76, minHeight: 40, borderWidth: 1, borderRadius: radius.control, paddingHorizontal: 8, fontSize: 13 }, input: { minHeight: 46, borderWidth: 1, borderRadius: radius.control, paddingHorizontal: 12, fontFamily: 'Inter_400Regular', fontSize: 14 }, button: { minHeight: 46, borderRadius: radius.control, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#fff', fontFamily: 'Inter_700Bold' }, disabled: { opacity: .6 }, goal: { gap: 9 }, link: { fontFamily: 'Inter_700Bold', fontSize: 12 }, remove: { fontFamily: 'Inter_700Bold', fontSize: 11 }, progress: { height: 7, borderRadius: 99, overflow: 'hidden' }, progressFill: { height: 7, borderRadius: 99 }, cta: { borderRadius: radius.control, minHeight: 50, alignItems: 'center', justifyContent: 'center' }, ctaText: { fontFamily: 'Inter_700Bold', color: '#fff' } });
